# #############################################################################
#   @Author        : fineemb
#   @Github        : https://github.com/fineemb
#   @Description   : 
#   @Date          : 2019-09-07 02:58:01
#   @LastEditors   : fineemb
#   @LastEditTime  : 2020-01-31 21:43:16
# #############################################################################


set_voice:
  description: 设置蜂鸣器。
  fields:
    entity_id:
      description: 指定养生壶ID.
      example: 'health_pot.ysh'
    voice:
      description: 设置开关,on/off.
      example: 'on'
set_work:
  description: 指定工作模式,或者关闭。可以指定保温温度和时长,以及预约时间
  fields:
    entity_id:
      description: 指定养生壶ID.
      example: 'health_pot.ysh'
    status:
      description: 设置工作状态,1-5 ( 1:预约, 2:烹饪, 3:暂停, 4:保温, 5:终止).
      example: '2'
    id: 
      description: 模式id,可以有24个模式.1-8以及11-26
      example: '8'
    keep_temp: 
      description: 保温温度,1-99
      example: '80'
    keep_time: 
      description: 保温时长,单位为小时1-12
      example: '12'
delete_modes:
  description: 删除指定自定义模式
  fields:
    entity_id:
      description: 指定养生壶ID.
      example: 'health_pot.ysh'
    modes:
      description: 模式id,有7个自定义模式.1-8
      example: '1'
set_mode_sort:
  description: 设置模式排序
  fields:
    entity_id:
      description: 指定养生壶ID.
      example: 'health_pot.ysh'
    sort:
      description: 所有模式ID的顺序
      example: '11-12-13-23-15-16-17-18-20-26-21-14-19-25-24-22-1-2'
set_mode:
  description: 配置自定义模式属性。可以指定火力和时长
  fields:
    entity_id:
      description: 指定养生壶ID.
      example: 'health_pot.ysh'
    id: 
      description: 模式id,可以有7个自定义模式.1-8
      example: '1'
    temp: 
      description: 火力,1-99
      example: '99'
    time: 
      description: 时长,单位为分钟
      example: '60'